// <auto-generated />
using System;
using GymManager.api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymManager.api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260313004101_entrenadores")]
    partial class entrenadores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymManager.api.Models.Entrenador", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DNI"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RCPExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DNI");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("GymManager.api.Models.Patologia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Patalogias");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Hipertensión Arterial"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Problemas Cardíacos"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Lesiones de Columna"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Lesiones Articulares"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Asma / Problemas Respiratorios"
                        },
                        new
                        {
                            id = 6,
                            nombre = "Diabetes"
                        },
                        new
                        {
                            id = 7,
                            nombre = "Cirugías Recientes"
                        },
                        new
                        {
                            id = 8,
                            nombre = "Mareos / Vértigo"
                        },
                        new
                        {
                            id = 9,
                            nombre = "Embarazo"
                        },
                        new
                        {
                            id = 10,
                            nombre = "Medicación Crónica"
                        });
                });

            modelBuilder.Entity("GymManager.api.Models.Socio", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DNI"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("DNI");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("GymManager.api.Models.Socio_Patologia", b =>
                {
                    b.Property<int>("Socio_DNI")
                        .HasColumnType("integer")
                        .HasColumnName("socio_dni");

                    b.Property<int>("Patologia_id")
                        .HasColumnType("integer")
                        .HasColumnName("patologia_id");

                    b.HasKey("Socio_DNI", "Patologia_id");

                    b.HasIndex("Patologia_id");

                    b.ToTable("socio_patologia");
                });

            modelBuilder.Entity("GymManager.api.Models.Socio_Patologia", b =>
                {
                    b.HasOne("GymManager.api.Models.Patologia", "Datos_Patologia")
                        .WithMany()
                        .HasForeignKey("Patologia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManager.api.Models.Socio", "Datos_Socio")
                        .WithMany()
                        .HasForeignKey("Socio_DNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datos_Patologia");

                    b.Navigation("Datos_Socio");
                });
#pragma warning restore 612, 618
        }
    }
}
